//
// Created by nbollom on 1/06/16.
//

#include "monsters.hpp"
#include <vector>

using namespace std;

namespace data {

    static const vector<Monster> monsters = {
            {"Anhkheg",           6,  "chitin"},
            {"Ant",               0,  "antenna"},
            {"Ape",               4,  "ass"},
            {"Baluchitherium",    14, "ear"},
            {"Beholder",          10, "eyestalk"},
            {"Black Pudding",     10, "saliva"},
            {"Blink Dog",         4,  "eyelid"},
            {"Cub Scout",         1,  "neckercheif"},
            {"Girl Scout",        2,  "cookie"},
            {"Boy Scout",         3,  "merit badge"},
            {"Eagle Scout",       4,  "merit badge"},
            {"Bugbear",           3,  "skin"},
            {"Bugboar",           3,  "tusk"},
            {"Boogie",            3,  "slime"},
            {"Camel",             2,  "hump"},
            {"Carrion Crawler",   3,  "egg"},
            {"Catoblepas",        6,  "neck"},
            {"Centaur",           4,  "rib"},
            {"Centipede",         0,  "leg"},
            {"Cockatrice",        5,  "wattle"},
            {"Couatl",            9,  "wing"},
            {"Crayfish",          0,  "antenna"},
            {"Demogorgon",        53, "tentacle"},
            {"Jubilex",           17, "gel"},
            {"Manes",             1,  "tooth"},
            {"Orcus",             27, "wand"},
            {"Succubus",          6,  "bra"},
            {"Vrock",             8,  "neck"},
            {"Hezrou",            9,  "leg"},
            {"Glabrezu",          10, "collar"},
            {"Nalfeshnee",        11, "tusk"},
            {"Marilith",          7,  "arm"},
            {"Balor",             8,  "whip"},
            {"Yeenoghu",          25, "flail"},
            {"Asmodeus",          52, "leathers"},
            {"Baalzebul",         43, "pants"},
            {"Barbed Devil",      8,  "flame"},
            {"Bone Devil",        9,  "hook"},
            {"Dispater",          30, "matches"},
            {"Erinyes",           6,  "thong"},
            {"Geryon",            30, "cornucopia"},
            {"Malebranche",       5,  "fork"},
            {"Ice Devil",         11, "snow"},
            {"Lemure",            3,  "blob"},
            {"Pit Fiend",         13, "seed"},
            {"Anklyosaurus",      9,  "tail"},
            {"Brontosaurus",      30, "brain"},
            {"Diplodocus",        24, "fin"},
            {"Elasmosaurus",      15, "neck"},
            {"Gorgosaurus",       13, "arm"},
            {"Iguanadon",         6,  "thumb"},
            {"Megalosaurus",      12, "jaw"},
            {"Monoclonius",       8,  "horn"},
            {"Pentasaurus",       12, "head"},
            {"Stegosaurus",       18, "plate"},
            {"Triceratops",       16, "horn"},
            {"Tyranosauraus Rex", 18, "forearm"},
            {"Djinn",             7,  "lamp"},
            {"Doppleganger",      4,  "face"},
            {"Black Dragon",      7,  "*"},
            {"Plaid Dragon",      7,  "sporrin"},
            {"Blue Dragon",       9,  "*"},
            {"Beige Dragon",      9,  "*"},
            {"Brass Dragon",      7,  "pole"},
            {"Tin Dragon",        8,  "*"},
            {"Bronze Dragon",     9,  "medal"},
            {"Chromatic Dragon",  16, "scale"},
            {"Copper Dragon",     8,  "loafer"},
            {"Gold Dragon",       8,  "filling"},
            {"Green Dragon",      8,  "*"},
            {"Platinum Dragon",   21, "*"},
            {"Red Dragon",        10, "cocktail"},
            {"Silver Dragon",     10, "*"},
            {"White Dragon",      6,  "tooth"},
            {"Dragon Turtle",     13, "shell"},
            {"Dryad",             2,  "acorn"},
            {"Dwarf",             1,  "drawers"},
            {"Eel",               2,  "sashimi"},
            {"Efreet",            10, "cinder"},
            {"Sand Elemental",    8,  "glass"},
            {"Bacon Elemental",   10, "bit"},
            {"Porn Elemental",    12, "lube"},
            {"Cheese Elemental",  14, "curd"},
            {"Hair Elemental",    16, "follicle"},
            {"Swamp Elf",         1,  "lilypad"},
            {"Brown Elf",         1,  "tusk"},
            {"Sea Elf",           1,  "jerkin"},
            {"Ettin",             10, "fur"},
            {"Frog",              0,  "leg"},
            {"Violet Fungi",      3,  "spore"},
            {"Gargoyle",          4,  "gravel"},
            {"Gelatinous Cube",   4,  "jam"},
            {"Ghast",             4,  "vomit"},
            {"Ghost",             10, "*"},
            {"Ghoul",             2,  "muscle"},
            {"Humidity Giant",    12, "drops"},
            {"Beef Giant",        11, "steak"},
            {"Quartz Giant",      10, "crystal"},
            {"Porcelain Giant",   9,  "fixture"},
            {"Rice Giant",        8,  "grain"},
            {"Cloud Giant",       12, "condensation"},
            {"Fire Giant",        11, "cigarettes"},
            {"Frost Giant",       10, "snowman"},
            {"Hill Giant",        8,  "corpse"},
            {"Stone Giant",       9,  "hatchling"},
            {"Storm Giant",       15, "barometer"},
            {"Mini Giant",        4,  "pompadour"},
            {"Gnoll",             2,  "collar"},
            {"Gnome",             1,  "hat"},
            {"Goblin",            1,  "ear"},
            {"Grid Bug",          1,  "carapace"},
            {"Jellyrock",         9,  "seedling"},
            {"Beer Golem",        15, "foam"},
            {"Oxygen Golem",      17, "platelet"},
            {"Cardboard Golem",   14, "recycling"},
            {"Rubber Golem",      16, "ball"},
            {"Leather Golem",     15, "fob"},
            {"Gorgon",            8,  "testicle"},
            {"Gray Ooze",         3,  "gravy"},
            {"Green Slime",       2,  "sample"},
            {"Griffon",           7,  "nest"},
            {"Banshee",           7,  "larynx"},
            {"Harpy",             3,  "mascara"},
            {"Hell Hound",        5,  "tongue"},
            {"Hippocampus",       4,  "mane"},
            {"Hippogriff",        3,  "egg"},
            {"Hobgoblin",         1,  "patella"},
            {"Homonculus",        2,  "fluid"},
            {"Hydra",             8,  "gyrum"},
            {"Imp",               2,  "tail"},
            {"Invisible Stalker", 8,  "*"},
            {"Iron Peasant",      3,  "chaff"},
            {"Jumpskin",          3,  "shin"},
            {"Kobold",            1,  "penis"},
            {"Leprechaun",        1,  "wallet"},
            {"Leucrotta",         6,  "hoof"},
            {"Lich",              11, "crown"},
            {"Lizard Man",        2,  "tail"},
            {"Lurker",            10, "sac"},
            {"Manticore",         6,  "spike"},
            {"Mastodon",          12, "tusk"},
            {"Medusa",            6,  "eye"},
            {"Multicell",         2,  "dendrite"},
            {"Pirate",            1,  "booty"},
            {"Berserker",         1,  "shirt"},
            {"Caveman",           2,  "club"},
            {"Dervish",           1,  "robe"},
            {"Merman",            1,  "trident"},
            {"Mermaid",           1,  "gills"},
            {"Mimic",             9,  "hinge"},
            {"Mind Flayer",       8,  "tentacle"},
            {"Minotaur",          6,  "map"},
            {"Yellow Mold",       1,  "spore"},
            {"Morkoth",           7,  "teeth"},
            {"Mummy",             6,  "gauze"},
            {"Naga",              9,  "rattle"},
            {"Nebbish",           1,  "belly"},
            {"Neo-Otyugh",        11, "organ"},
            {"Nixie",             1,  "webbing"},
            {"Nymph",             3,  "hanky"},
            {"Ochre Jelly",       6,  "nucleus"},
            {"Octopus",           2,  "beak"},
            {"Ogre",              4,  "talon"},
            {"Ogre Mage",         5,  "apparel"},
            {"Orc",               1,  "snout"},
            {"Otyugh",            7,  "organ"},
            {"Owlbear",           5,  "feather"},
            {"Pegasus",           4,  "aileron"},
            {"Peryton",           4,  "antler"},
            {"Piercer",           3,  "tip"},
            {"Pixie",             1,  "dust"},
            {"Man-o-war",         3,  "tentacle"},
            {"Purple Worm",       15, "dung"},
            {"Quasit",            3,  "tail"},
            {"Rakshasa",          7,  "pajamas"},
            {"Rat",               0,  "tail"},
            {"Remorhaz",          11, "protrusion"},
            {"Roc",               18, "wing"},
            {"Roper",             11, "twine"},
            {"Rot Grub",          1,  "eggsac"},
            {"Rust Monster",      5,  "shavings"},
            {"Satyr",             5,  "hoof"},
            {"Sea Hag",           3,  "wart"},
            {"Silkie",            3,  "fur"},
            {"Shadow",            3,  "silhouette"},
            {"Shambling Mound",   10, "mulch"},
            {"Shedu",             9,  "hoof"},
            {"Shrieker",          3,  "stalk"},
            {"Skeleton",          1,  "clavicle"},
            {"Spectre",           7,  "vestige"},
            {"Sphinx",            10, "paw"},
            {"Spider",            0,  "web"},
            {"Sprite",            1,  "can"},
            {"Stirge",            1,  "proboscis"},
            {"Stun Bear",         5,  "tooth"},
            {"Stun Worm",         2,  "trode"},
            {"Su-monster",        5,  "tail"},
            {"Sylph",             3,  "thigh"},
            {"Titan",             20, "sandal"},
            {"Trapper",           12, "shag"},
            {"Treant",            10, "acorn"},
            {"Triton",            3,  "scale"},
            {"Troglodyte",        2,  "tail"},
            {"Troll",             6,  "hide"},
            {"Umber Hulk",        8,  "claw"},
            {"Unicorn",           4,  "blood"},
            {"Vampire",           8,  "pancreas"},
            {"Wight",             4,  "lung"},
            {"Will-o-the-Wisp",   9,  "wisp"},
            {"Wraith",            5,  "finger"},
            {"Wyvern",            7,  "wing"},
            {"Xorn",              7,  "jaw"},
            {"Yeti",              4,  "fur"},
            {"Zombie",            2,  "forehead"},
            {"Wasp",              0,  "stinger"},
            {"Rat",               1,  "tail"},
            {"Bunny",             0,  "ear"},
            {"Moth",              0,  "dust"},
            {"Beagle",            0,  "collar"},
            {"Midge",             0,  "corpse"},
            {"Ostrich",           1,  "beak"},
            {"Billy Goat",        1,  "beard"},
            {"Bat",               1,  "wing"},
            {"Koala",             2,  "heart"},
            {"Wolf",              2,  "paw"},
            {"Whippet",           2,  "collar"},
            {"Uruk",              2,  "boot"},
            {"Poroid",            4,  "node"},
            {"Moakum",            8,  "frenum"},
            {"Fly",               0,  "*"},
            {"Hogbird",           3,  "curl"}
    };

    static uniform_int_distribution<unsigned long> distribution(0, monsters.size() - 1);

    Monster get_random_monster(const std::shared_ptr<std::mt19937_64>& engine) {
        const unsigned long value = distribution(*engine);
        return monsters[value];
    }

}
